# 这个只是我开发core时测试使用，实际发布时，这个可以去掉，因为在引用此core时，这个值会被覆盖掉
server:
  port: 8034
  servlet:
    context-path: /yhchat
yhchat-config:
  httpUrl: "https://chat-go.jwzhd.com/open-apis/v1"
  webSocketUrl: "wss://ws.jwzhd.com/subscribe"


yhchat:
  # 是否打印原始消息日志
  printLog: true
  token: "33b3b0e83a964fe290fde6ef5b1a2e70"
  # 接入模式，空或者1=http，2=websocket
  mode: "2"


